#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  apps_runbook.sh apply --server-fqdn HOST --repo-path PATH --server-user USER
  apps_runbook.sh status --server-fqdn HOST --repo-path PATH
  apps_runbook.sh test --server-fqdn HOST

Configures the static camera web apps from docs/APPS.md. The runtime registry is
built from the MCP HTTP server and served from /etc/onvif-mcp/camera_registry.json.
USAGE
}
cmd="${1:-}"; [[ -n "$cmd" ]] || { usage; exit 64; }
[[ "$cmd" == "-h" || "$cmd" == "--help" ]] && { usage; exit 0; }
shift || true
server_fqdn=""; repo_path=""; server_user=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-fqdn) server_fqdn="${2:?missing --server-fqdn value}"; shift 2 ;;
    --repo-path) repo_path="${2:?missing --repo-path value}"; shift 2 ;;
    --server-user) server_user="${2:?missing --server-user value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 64 ;;
  esac
done
require_arg() { local name="$1" value="$2"; [[ -n "$value" ]] || { echo "Missing required argument: $name" >&2; exit 64; }; }
project_dir() { printf '%s' "${repo_path%/}"; }

install_packages() {
  missing=(); command -v curl >/dev/null 2>&1 || missing+=(curl); command -v python3 >/dev/null 2>&1 || missing+=(python3); command -v nginx >/dev/null 2>&1 || missing+=(nginx)
  if [[ ${#missing[@]} -gt 0 ]]; then sudo apt-get update; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "${missing[@]}"; fi
}

write_registry() {
  require_arg --server-fqdn "$server_fqdn"
  sudo install -d -o root -g root -m 0755 /etc/onvif-mcp
  tmp="$HOME/.camera_registry.json.$$"
  python3 - "$server_fqdn" > "$tmp" <<'PY'
import json, sys, urllib.request, datetime
server=sys.argv[1]
def mcp_call(name, args=None):
    url=f'http://{server}/mcp'
    init={"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"apps-runbook","version":"1"}}}
    with urllib.request.urlopen(urllib.request.Request(url, data=json.dumps(init).encode(), headers={'Content-Type':'application/json','Accept':'text/event-stream, application/json'}, method='POST'), timeout=60) as r:
        sid=r.headers.get('mcp-session-id'); r.read()
    try:
        note={"jsonrpc":"2.0","method":"notifications/initialized"}
        urllib.request.urlopen(urllib.request.Request(url, data=json.dumps(note).encode(), headers={'Content-Type':'application/json','Accept':'text/event-stream, application/json','mcp-session-id':sid}, method='POST'), timeout=30).read()
    except Exception: pass
    payload={"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":name,"arguments":args or {}}}
    with urllib.request.urlopen(urllib.request.Request(url, data=json.dumps(payload).encode(), headers={'Content-Type':'application/json','Accept':'text/event-stream, application/json','mcp-session-id':sid}, method='POST'), timeout=180) as r:
        body=r.read().decode()
    data='\n'.join(line[5:].strip() for line in body.splitlines() if line.startswith('data:'))
    return json.loads(data)['result']['content'][0]['text']
text=mcp_call('get_cameras')
cameras=[]
for part in text.split('\n--\n'):
    part=part.strip()
    if not part: continue
    cam=json.loads(part)
    profiles=cam.get('profiles', [])
    if not profiles: continue
    main=profiles[0]
    sub=profiles[1] if len(profiles) > 1 else main
    cameras.append({
        'hostname': cam.get('hostname') or cam.get('serial_number'),
        'ip_address': cam.get('ip_address'),
        'manufacturer': cam.get('manufacturer'),
        'model': cam.get('model'),
        'serial_number': cam.get('serial_number'),
        'media_profile_token': main.get('token'),
        'substream_profile_token': sub.get('token'),
        'media_player_url': main.get('web_player_url') or f'http://{server}/webrtc/{cam["serial_number"]}/{main["token"]}/',
        'substream_player_url': sub.get('web_player_url') or f'http://{server}/webrtc/{cam["serial_number"]}/{sub["token"]}/',
        'snapshot_url': main.get('web_snapshot_url') or f'http://{server}/snapshot/{cam["serial_number"]}/{main["token"]}/',
    })
if not cameras: raise SystemExit('No cameras discovered')
print(json.dumps({'description':'Runtime camera registry generated by scripts/APPS/apps_runbook.sh', 'generated': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'cameras': cameras}, indent=2))
PY
  sudo install -o root -g root -m 0644 "$tmp" /etc/onvif-mcp/camera_registry.json
  rm -f "$tmp"
}

configure_nginx_user() {
  require_arg --server-user "$server_user"
  if ! getent passwd webcam >/dev/null; then sudo useradd --system --no-create-home --shell /usr/sbin/nologin webcam; fi
  sudo usermod -aG "$server_user" webcam
  sudo python3 - <<'PY'
from pathlib import Path
p=Path('/etc/nginx/nginx.conf')
text=p.read_text()
if 'user www-data;' in text:
    text=text.replace('user www-data;', 'user webcam;', 1)
elif not any(line.startswith('user ') for line in text.splitlines()):
    text='user webcam;\n'+text
p.write_text(text)
PY
}

ensure_nginx_locations() {
  require_arg --server-fqdn "$server_fqdn"; require_arg --repo-path "$repo_path"
  dir="$(project_dir)"; test -d "$dir/apps/cameras"; test -d "$dir/apps/multiview"
  sudo python3 - "$server_fqdn" "$dir" <<'PY'
import pathlib, re, sys
fqdn, project = sys.argv[1:3]
p=pathlib.Path('/etc/nginx/sites-available/camera')
text=p.read_text() if p.exists() else f'server {{\n    listen 80;\n    server_name {fqdn};\n}}\n'
text=re.sub(r'(?m)^\s*server_name\s+[^;]+;', f'    server_name {fqdn};', text, count=1)
blocks=[]
if 'location = /cameras' not in text:
    blocks.append('''

    location = /cameras { return 301 /cameras/; }
    location = /multiview { return 301 /multiview/; }
''')
if 'location /cameras/' not in text:
    blocks.append(f'''

    location /cameras/ {{
        alias {project}/apps/cameras/;
    }}

    location /multiview/ {{
        alias {project}/apps/multiview/;
    }}
''')
if 'location = /outputs/camera_registry.json' not in text:
    blocks.append('''

    location = /outputs/camera_registry.json {
        alias /etc/onvif-mcp/camera_registry.json;
    }

    location /outputs/ {
        return 404;
    }
''')
if blocks:
    idx=text.rfind('}')
    if idx == -1: raise SystemExit('No closing brace in nginx camera site')
    text=text[:idx]+''.join(blocks)+text[idx:]
p.write_text(text)
PY
  sudo ln -sfn /etc/nginx/sites-available/camera /etc/nginx/sites-enabled/camera
  sudo nginx -t
  sudo systemctl restart nginx
}

print_status() {
  echo '== nginx =='; systemctl is-enabled nginx 2>/dev/null || true; systemctl is-active nginx 2>/dev/null || true; grep -n '^user ' /etc/nginx/nginx.conf || true
  echo '== registry =='; sudo stat -c '%a %U:%G %n' /etc/onvif-mcp/camera_registry.json 2>/dev/null || true; sudo python3 -c 'import json; print(len(json.load(open("/etc/onvif-mcp/camera_registry.json"))["cameras"]))' 2>/dev/null || true
  echo '== endpoints =='; for u in /cameras/ /multiview/ /outputs/camera_registry.json /cameras/styles.css /cameras/app.js /multiview/app.js; do printf '%-36s ' "$u"; curl -s -o /dev/null -w '%{http_code}\n' "http://127.0.0.1$u" || true; done
}

test_apps() {
  require_arg --server-fqdn "$server_fqdn"
  failed=0
  for u in /cameras/ /multiview/ /outputs/camera_registry.json /cameras/styles.css /cameras/app.js /multiview/app.js; do
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://$server_fqdn$u")"
    echo "$u $code"
    [[ "$code" == 200 ]] || failed=1
  done
  for u in /cameras /multiview; do
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://$server_fqdn$u")"
    echo "$u $code"
    [[ "$code" == 301 ]] || failed=1
  done
  python3 - <<'PY'
import json, urllib.request
j=json.load(urllib.request.urlopen('http://127.0.0.1/outputs/camera_registry.json', timeout=10))
assert j['cameras']
for c in j['cameras']:
    assert c.get('media_player_url','').startswith('http://') and c['media_player_url'].endswith('/')
print('registry-ok cameras=%d' % len(j['cameras']))
PY
  exit "$failed"
}

case "$cmd" in
  apply)
    require_arg --server-fqdn "$server_fqdn"; require_arg --repo-path "$repo_path"; require_arg --server-user "$server_user"
    install_packages; write_registry; configure_nginx_user; ensure_nginx_locations; print_status ;;
  status) print_status ;;
  test) test_apps ;;
  *) echo "Unknown command: $cmd" >&2; usage >&2; exit 64 ;;
esac
